BRL_Portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('email/', views.email, name='email'),
    path('RD_Project/', include('RD_Projects.urls'), name="RD_Project"),
    path('publications/', include('publications.urls'), name="publications"),
    path('blogs/', include('blogs.urls'), name='blog'),
    path('staff/', include('staff.urls'), name='staff'),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

RD_Projects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

# app_name = "RD_Project"
app_name = 'RD_Project'
urlpatterns = [
    path('Project_Domains/', views.project_domains, name='Project_domains'),
    path('projects_all', views.projects_all, name='projects_all'),
    path('projects_single/<str:id>', views.project_single, name='projects_single'),
    path('services/', views.services, name="services"),
    path('services/<str:id>', views.service_single, name="services_single"),
    path('get_project_detail/', views.get_project_detail, name="get_project_detail"),
    path('get_service_detail/', views.get_service_detail, name="get_service_detail")
]

blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "blog"
urlpatterns = [
    path('blog_all/', views.blog_all, name='blog_all'),
    path('blog_single/<int:id>', views.blog_single, name='blog_single'),
]

RD_Projects/models.py
from django.db import models
from ckeditor.fields import RichTextField
from tinymce.models import HTMLField
# Create your models here.


class productDomain(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class serviceDomain(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to='images/Project_pics', null=True, blank=True)
    video = models.FileField(upload_to='images/Project_videos', null=True, blank=True)
    voucher = models.ImageField(upload_to='images/Project_vouchers', null=True, blank=True)
    voucherPDF = models.FileField(upload_to='images/Project_voucherPDF', null=True, blank=True)
    domain = models.ForeignKey(productDomain, default=1, on_delete=models.CASCADE)
    content = RichTextField()


class Service(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to='images/Service_pics', null=True, blank=True)
    voucher = models.ImageField(upload_to='images/Service_vouchers', null=True, blank=True)
    voucherPDF = models.FileField(upload_to='images/Service_voucherPDF', null=True, blank=True)
    domain = models.ForeignKey(serviceDomain, default=1, on_delete=models.CASCADE)
    content = RichTextField()

RD_Projects/views.py
import json

from django.shortcuts import render
from RD_Projects.models import *
from django.http import HttpResponse, JsonResponse
import json

from django.core import serializers

# Create your views here.
def project_domains(request):
    domains = Project.objects.all()
    dict_obj = {'domains': domains}
    return render(request, 'RD_Projects/projects-Domain.html', dict_obj)


def projects_all(request):
    domains = productDomain.objects.all()
    projects = Project.objects.all()
    dict_obj = {'domains': domains, 'projects': projects}
    return render(request, 'RD_Projects/projects-all.html', dict_obj)


# def project_single(request, id):
#     project = Project.objects.filter(id=id)
#     print(project)
#     dict_obj = {'project': project}
#     return render(request, 'RD_Projects/project-single.html', dict_obj)

def project_single(request, id):
    project = Project.objects.filter(id=id)
    print(project)
    dict_obj = {'project': project}
    return HttpResponse("Success")


def service_single(request, id):
    project = Project.objects.filter(id=id)
    print(project)
    dict_obj = {'project': project}
    return HttpResponse("Success")


def services(request):
    domains = serviceDomain.objects.all()
    services = Service.objects.all()
    dict_obj = {'domains': domains, 'services': services}
    return render(request, 'RD_Projects/services.html', dict_obj)


# def service_single(request, id):
#     service = Service.objects.filter(id=id)
#     dict_obj = {'service': service}
#     return render(request, 'RD_Projects/service-single.html', dict_obj)


def get_project_detail(request):
    id = request.GET['id']
    project = Project.objects.filter(id=id)
    tmpJson = serializers.serialize("json",project)
    tmpObj = json.loads(tmpJson)

    return HttpResponse(json.dumps(tmpObj))


def get_service_detail(request):
    id = request.GET['id']
    service = Service.objects.filter(id=id)
    tmpJson = serializers.serialize("json",service)
    tmpObj = json.loads(tmpJson)

    return HttpResponse(json.dumps(tmpObj))

RD_Projects/templates/RD_Projects/product-category.html
{% extends 'basic.html' %}
{% load static %}

{% block style %}

        <style>


        .card {
            background: #EEE;
            border-radius: 20px;
            border: 1px solid #0f2a5f;
            color: rgba(250, 250, 250, 0.8);
            margin-bottom: 5rem;
        }

         .card-img {
             height: 100px;
             width: 100%;
            border-top-left-radius: 20px;
            border-bottom-left-radius: 20px;

        }


    </style>

{% endblock %}


{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-5">
                            <img class="card-img" src="{% static 'img/ES.jpeg' %}" alt="...">
                        </div>
                        <div class="col-md-7">
                            <div class="card-body">
                                <h1 class="card-title"></h1>
{#                                <p class="card-text">This is a wider card with supporting text below as a natural#}
{#                                    lead-in to#}
{#                                    additional content. This content is a little bit longer.</p>#}
                                <p class="card-text">
                                    <h3 class="">Attendance Solutions</h3>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-2"></div>
            <div class="col-md-5 row">
                    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-5">
                <img class="card-img" src="{% static 'img/ES.jpeg' %}" alt="...">
            </div>
            <div class="col-md-7">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
{#                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to#}
{#                        additional content. This content is a little bit longer.</p>#}
                    <p class="card-text">
                        <small class="text-muted">Last updated 3 mins ago</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
            </div>
{#            <div class="col-lg-1"></div>#}
{#            <div class="col-md-1"></div>#}
        </div>
    </div>




{% endblock %}

RD_Projects/templates/RD_Projects/project-single.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}

    <style>
    .bg-section {
        height: 400px;
    }
    .product-image{
        max-width: 100%;
        max-height: 100%;
        {#height: 100%;#}
        width: 100%;
        display: block;
        margin-top: 70px;

    }
    </style>



    {% for p in project %}
        <div class="bg-section mb-3">
            <img class="product-image" src="{{ p.image.url }}">
        </div>
    {% endfor %}



    <!-- Portfolio -->
    <div id="portfolio" class="section sm-padding">
        <!-- Container -->
        <div class="container">
            <!-- Row -->
            <div class="row">
                {% for p in project %}
                    <!-- Section header -->
                    <div class="section-header text-center">
                        <h2 class="title">{{ p.name }}</h2>
                    </div>
                    <!-- /Section header -->
                    <!-- Work -->
                    <div class="col-md-8">

                        <div><h3>Description</h3></div>
                        <div>{{ p.content|safe }}</div>
                        {% if p.video %}
                            <video poster="{% static p.image.url %}" width="500px" height="350px"
                                   controls="controls" preload="none" onclick="this.play()">
                                <source type="video/mp4" src="{{ p.video.url }}">
                            </video>
                        {% endif %}

                    </div>
                {% endfor %}
                <div class="col-md-4 voucher work text-center">
                    {% for p in project %}
                        {% if p.voucherPDF %}
                            <button class="btn btn-lg main-btn" type="submit"
                                    onclick="window.location.href='{{ p.voucherPDF.url }}'"><i
                                    class="fa fa-download"> Download Brochure</i>
                            </button>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <!-- /Row -->
        </div>
        <!-- /Container -->

    </div>
    <!-- /Portfolio -->


    <!-- modal -->
    <div class="modal" tabindex="-1">
        <div class="modal-dialog">
            {% for p in project %}
                {% if p.voucher %}
                    <div class="modal-content">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="position: absolute; top: 5px; right: 5px"></button>
                        <img src="{{ p.voucher.url }}">
                        <a class="btn btn-lg main-btn"
                           href="{{ p.voucher.url }}" download="broucher">
                            <i class="fa fa-download"> Download Brochure</i>
                        </a>
                    </div>
                {% endif %}
            {% endfor %}

        </div>
    </div>
    <!-- /modal -->

{% endblock %}

{% block script %}
  <script>
      $(document).ready(function () {
          {% for p in project %}
              {% if p.voucher %}
                  $(".modal").modal('show');
              {% endif %}
          {% endfor %}
      });
  </script>
{% endblock %}

RD_Projects/templates/RD_Projects/projects-Domain.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}

    <!-- Portfolio -->
    <div id="portfolio" class="section md-padding bg-grey">

        <!-- Container -->
        <div class="container">

            <!-- Row -->
            <div class="row">

                <!-- Section header -->
                <div class="section-header text-center">
                    <h2 class="title">Featured Domains</h2>
                </div>
                <!-- /Section header -->

                {% for domain in domains %}
                <!-- Work -->
                <div class="col-md-4 col-xs-6 work">
                    <img class="img-responsive" src="{{ domain.image.url }}" alt="" style="height: 350px">
                    <div class="overlay"></div>
                    <div class="work-content">
                        <span>Category</span>
                        <h3>{{ domain.name   }}</h3>
                        <div class="work-link">
                            <a href="{% url 'RD_Project:projects_all' domain.id %}"><i class="fa fa-external-link"></i></a>
                            <a class="lightbox" href="{{ domain.image }}"><i class="fa fa-search"></i></a>
                        </div>
                    </div>
                </div>
                <!-- /Work -->
                {% endfor %}

                <!-- Work -->
                <div class="col-md-4 col-xs-6 work">
                    <img class="img-responsive" src="{% static 'img/work11.jpg' %}" alt="" width="600px" height="600px">
                    <div class="overlay"></div>
                    <div class="work-content">
                        <span>Category</span>
                        <h3>Phylogenetics</h3>
                        <div class="work-link">
                            <a href="#"><i class="fa fa-external-link"></i></a>
                            <a class="lightbox" href="{% static 'img/work1.jpg' %}"><i class="fa fa-search"></i></a>
                        </div>
                    </div>
                </div>
                <!-- /Work -->

            </div>
            <!-- /Row -->

        </div>
        <!-- /Container -->

    </div>
    <!-- /Portfolio -->

{% endblock %}

RD_Projects/templates/RD_Projects/projects-all.html
{% extends 'basic.html' %}
{% load static %}

{% block style %}

    <!-- Custom Page stylesheet -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/products-services-style.css' %}"/>
    <style>
        #broucher-btn {

            opacity: 0;
        }

         .imageDiv img:hover{
            opacity: 0.3;
        }

        #imageDiv:hover #broucher-btn {
            /*opacity: 0.4;*/
            opacity: 1;
        }


    </style>
{% endblock %}


{% block content %}

    <div class="container mx-auto md-padding">
        <div class="row">

            <!-- Section header -->
            <div class="section-header text-center">
                <h2 class="title">Products</h2>
            </div>
            <!-- /Section header -->


            <div id="myBtnContainer" class="container">
                <div class="text-center" style="margin-bottom: 30px">
                    {% for domain in domains %}
                        <button class="btn tab-btn"
                                onclick="filterSelection('{{ domain.name }}')">{{ domain.name }}</button>
                    {% endfor %}
                </div>
            </div>


            {% for project in projects %}
                <div class="col-md-3 column {{ project.domain.name }}">
                    <div class="card">

                        <div class="card-head">
                            {% if project.image %}
                                <img class="card-img-top1" src="{{ project.image.url }}"
                                     alt="">
                            {% elif project.name != None %}
                                <img class="card-img-top1" src="{% static 'images/images/item-1.jpg' %}">
                            {% endif %}
                        </div>

                        <div class="card-body">
                            <div class="heading-wrapper h50"><h5 class="card-subtitle">{{ project.name }}</h5></div>
                            <div class="text-wrapper"><p class="card-text">{{ project.description }}</p>
                            </div>

                        </div>

                        <div class="card-footer" style="border-bottom-right-radius: 20px;
    border-bottom-left-radius: 20px;">
                            <a class="btn btn-sm main-btn1 modal-btn" data-id="{{ project.id }}"><i
                                    class="fa fa-arrow-circle-right"></i> View Details</a>
                        </div>

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>






    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable modal-xl modal-center shadow-lg">
            <div class="modal-content">
                <div class="modal-header" style="border-bottom: none; padding-bottom: 0px">
                    <h5 class="modal-title" id="staticBackdropLabel"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="padding-top: 0px">
                    <div class="container">
                        <div class="row">
                            <div class="contentDiv row">

                                <div class="test col-md-8"></div>
                                <div id="imageDiv" class="imageDiv col-md-4">
                                    <img src="#" style="max-width: 100%; margin-bottom: 10px">
                                    <a class="btn btn-sm btn-danger broucher-btn" id="broucher-btn"
                                       href="" download="broucher" style="position: absolute; top: 50%; left: 75%; background-color: red; font-family: Arial, Helvetica, Sans-Serif">
                                        <i class="fa fa-download"></i> Download Brochure
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer" style="border-top: none">
{#                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>#}
                </div>
            </div>
        </div>
    </div>
    <!-- /Modal -->


{% endblock %}


{% block script %}
    <script>


        filterSelection('All') // Execute the function and show all columns
        $('.tab-btn:first-child').addClass("active");

        function filterSelection(c) {
            var x, i;
            x = document.getElementsByClassName("column");
            if (c == 'All') c = "";
            // Add the "show" class (display:block) to the filtered elements, and remove the "show" class from the elements that are not selected
            for (i = 0; i < x.length; i++) {
                w3RemoveClass(x[i], "show");
                console.log(x[i].className.indexOf(c));
                if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
            }
        }

        // Show filtered elements
        function w3AddClass(element, name) {
            var i, arr1, arr2;
            arr1 = element.className.split(" ");
            arr2 = name.split(" ");
            for (i = 0; i < arr2.length; i++) {
                if (arr1.indexOf(arr2[i]) == -1) {
                    element.className += " " + arr2[i];
                }
            }
        }

        // Hide elements that are not selected
        function w3RemoveClass(element, name) {
            var i, arr1, arr2;
            arr1 = element.className.split(" ");
            arr2 = name.split(" ");
            for (i = 0; i < arr2.length; i++) {
                while (arr1.indexOf(arr2[i]) > -1) {
                    arr1.splice(arr1.indexOf(arr2[i]), 1);
                }
            }
            element.className = arr1.join(" ");
        }

        // Add active class to the current button (highlight it)
        var btnContainer = document.getElementById("myBtnContainer");
        var btns = btnContainer.getElementsByClassName("btn");
        for (var i = 0; i < btns.length; i++) {
            btns[i].addEventListener("click", function () {
                var current = document.getElementsByClassName("active");
                current[0].className = current[0].className.replace(" active", "");
                this.className += " active";
            });
        }
    </script>

    <script>
        $('.modal-btn').on('click', function (e) {
            e.preventDefault();
            var button = $(this);
            var id = button.attr('data-id');


            $.ajax({
                url: 'get_project_detail/',
                content_type: 'application/json',
                type: 'GET',
                data: {
                    id: id,
                },
                success: function (res) {
                    var data = JSON.parse(res);
                    data = data[0];
                    data = data['fields'];
                    console.log(data.name)

                    $('.modal-title').text(data.name);

                    $('.test').empty();
                    $('.test').append(data.content);
                    $('.imageDiv img').attr('src',"../static/"+data.voucher);
                    $('.broucher-btn').attr('href',"../static/"+data.voucher);
                    $(".modal").modal('show');

                }
            });


        });


        $('.modal').on('click', function () {
             $(".modal").modal('hide');
        });


    </script>
{% endblock %}

RD_Projects/templates/RD_Projects/services.html
{% extends 'basic.html' %}
{% load static %}

{% block style %}

        <!-- Custom Page stylesheet -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/products-services-style.css' %}"/>

        <style>
        #broucher-btn {

            opacity: 0;
        }

         .imageDiv img:hover{
            opacity: 0.5;
        }

        #imageDiv:hover #broucher-btn {
            /*opacity: 0.4;*/
            opacity: 1;
        }


    </style>

{#    <style>#}
{##}
{##}
{#        .card {#}
{#            border-radius: 20px;#}
{#            border: 1px solid #0f2a5f;#}
{#            color: rgba(250, 250, 250, 0.8);#}
{#            margin-bottom: 5rem;#}
{#        }#}
{##}
{#        .card-head {#}
{#            height: 200px;#}
{#        }#}
{##}
{#        .card-img-top1 {#}
{#            padding: 10px ;#}
{#            max-width: 100%;#}
{#            max-height: 100%;#}
{#            height: 100%;#}
{#            width: 100%;#}
{#            object-fit: cover;#}
{#            border-radius: 20px;#}
            {#border-top-left-radius: 20px;#}
            {#border-top-right-radius: 20px;#}
{##}
{#        }#}
{##}
{#        .heading-wrapper {#}
{#            height: 50px;#}
{#            text-align: center;#}
{#            display: table;#}
{#            width: 100%;#}
{#        }#}
{##}
{#        .heading-wrapper h5{#}
{#            display: table-cell;#}
{#            vertical-align: middle;#}
{#        }#}
{##}
{#        .text-wrapper {#}
{#            height: 60px;#}
{#            text-align: center;#}
{#            display: table;#}
{#            width: 100%;#}
{#        }#}
{##}
{#        .text-wrapper p {#}
{#            display: table-cell;#}
{#            vertical-align: middle;#}
{#            line-height: 1.3;#}
{#        }#}
{#    </style>#}
{##}
{#    <style>#}
{##}
{##}
{#        .row {#}
{#            margin: 8px -16px;#}
{#        }#}
{##}
{#        .column {#}
        {#float: left;#}{#width: 33.33%;#} display: none; /* Hide columns by default */
{#        }#}
{##}
{#        /* Clear floats after rows */#}
{#        .row:after {#}
{#            content: "";#}
{#            display: table;#}
{#            clear: both;#}
{#        }#}
{##}
{#        /* The "show" class is added to the filtered elements */#}
{#        .show {#}
{#            display: block;#}
{#        }#}
{##}
{#        /* Style the buttons */#}
{#        .tab-btn {#}
{#            border: 1px;#}
{#            outline: none;#}
{#            padding: 12px 16px;#}
{#            background-color: white;#}
{#            cursor: pointer;#}
{#        }#}
{##}
{#        /* Add a grey background color on mouse-over */#}
{#        .tab-btn:hover {#}
{#            background-color: #F3581F;#}
{#        }#}
{##}
{#        /* Add a dark background color to the active button */#}
{#        .tab-btn.active {#}
{#            background-color: #0f2a5f;#}
{#            color: white;#}
{#        }#}
{#    </style>#}

{% endblock %}


{% block content %}



    <div class="container mx-auto mt-4 md-padding">
        <div class="row">

            <!-- Section header -->
            <div class="section-header text-center">
                <h2 class="title">Services</h2>
            </div>
            <!-- /Section header -->

            <div id="myBtnContainer" class="container">
                <div class="text-center" style="margin-bottom: 30px">
                {% for domain in domains %}
                    <button class="btn tab-btn"
                            onclick="filterSelection('{{ domain.name }}')">{{ domain.name }}</button>
                {% endfor %}
                </div>
            </div>

            {% for service in services %}
                <div class="col-md-3 column {{ service.domain.name }}">
                <div class="card">

                    <div class="card-head">
                        {% if service.image %}
                            <img class="card-img-top1" src="{{ service.image.url }}"
                                 alt="">
                        {% elif service.name != None %}
                            <img class="card-img-top1" src="{% static 'images/images/item-1.jpg' %}">
                        {% endif %}
                    </div>


                    <div class="card-body" style="">
                        <div class="heading-wrapper h70"><h5 class="card-subtitle mb-2">{{ service.name }}</h5></div>
                        <div class="text-wrapper"><p class="card-text">{{ service.description }}</p>
                        </div>
                    </div>

                    <div class="card-footer" style="border-bottom-right-radius: 20px;
    border-bottom-left-radius: 20px;">
                        <a    href="{% url 'RD_Project:get_service_detail' %}"  class="btn btn-sm main-btn1 modal-btn" data-id="{{ service.id }}"><i
                            class="fa fa-arrow-circle-right"></i> View Details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <!-- Modal -->
   <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable modal-xl modal-center shadow-lg">
            <div class="modal-content">
                <div class="modal-header" style="border-bottom: none; padding-bottom: 0px">
                    <h5 class="modal-title" id="staticBackdropLabel"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="padding-top: 0px">
                    <div class="container">
                        <div class="row">
                            <div class="contentDiv row" style="text-align: justify">

                                <div class="test col-md-8"></div>
                                <div id="imageDiv" class="imageDiv col-md-4">
                                    <img src="#" style="max-width: 100%; margin-bottom: 10px">
                                    <a class="btn btn-sm btn-danger broucher-btn" id="broucher-btn"
                                       href="" download="broucher" style="position: absolute; top: 50%; left: 75%; background-color: red; font-family: Arial, Helvetica, Sans-Serif">
                                        <i class="fa fa-download"> Download Brochure</i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer" style="border-top: none">
{#                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>#}
                </div>
            </div>
        </div>
    </div>
    <!-- /Modal -->


{% endblock %}


{% block script %}
<script>
filterSelection('All') // Execute the function and show all columns
$('.tab-btn:first-child').addClass("active");
function filterSelection(c) {
  var x, i;
  x = document.getElementsByClassName("column");
  if (c == 'All') c = "";
  // Add the "show" class (display:block) to the filtered elements, and remove the "show" class from the elements that are not selected
  for (i = 0; i < x.length; i++) {
    w3RemoveClass(x[i], "show");
    console.log(x[i].className.indexOf(c));
    if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
  }
}

// Show filtered elements
function w3AddClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    if (arr1.indexOf(arr2[i]) == -1) {
      element.className += " " + arr2[i];
    }
  }
}

// Hide elements that are not selected
function w3RemoveClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    while (arr1.indexOf(arr2[i]) > -1) {
      arr1.splice(arr1.indexOf(arr2[i]), 1);
    }
  }
  element.className = arr1.join(" ");
}

// Add active class to the current button (highlight it)
var btnContainer = document.getElementById("myBtnContainer");
var btns = btnContainer.getElementsByClassName("btn");
for (var i = 0; i < btns.length; i++) {
  btns[i].addEventListener("click", function(){
    var current = document.getElementsByClassName("active");
    current[0].className = current[0].className.replace(" active", "");
    this.className += " active";
  });
}
</script>

        <script>
        $('.modal-btn').on('click', function (e) {
            e.preventDefault();
            var button = $(this);
            var id = button.attr('data-id');
            console.log(id);
            var URL = button.attr('href');
            console.log(URL)
            $.ajax({
                url: URL,
                content_type: 'application/json',
                type: 'GET',
                data: {
                    id: id,
                },
                success: function (res) {
                    var data = JSON.parse(res);
                    data = data[0];
                    data = data['fields'];
                    console.log(data.name)

                    $('.modal-title').text(data.name);
                     $('.test').empty();
                    $('.test').append(data.content);
                    $('.imageDiv img').attr('src',"../../static/"+data.voucher);
                    $('.broucher-btn').attr('href',"../../static/"+data.voucher);
                    $(".modal").modal('show');

                }
            });


        });

        $('.modal').on('click', function () {
            $(".modal").modal('hide');
        });


    </script>
{% endblock %}