BRL_Portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('email/', views.email, name='email'),
    path('RD_Project/', include('RD_Projects.urls'), name="RD_Project"),
    path('publications/', include('publications.urls'), name="publications"),
    path('blogs/', include('blogs.urls'), name='blog'),
    path('staff/', include('staff.urls'), name='staff'),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "blog"
urlpatterns = [
    path('blog_all/', views.blog_all, name='blog_all'),
    path('blog_single/<int:id>', views.blog_single, name='blog_single'),
]

publications/urls.py
from django.urls import path, include
from . import views


app_name = "publication"
urlpatterns = [
    path('publications_all/', views.publications_all, name='publications_all'),
]

publications/models.py
from datetime import datetime
from django.db import models


# Create your models here.
class ResearchPaper(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    author = models.CharField(max_length=30)
    publishDate = models.DateField(default=datetime.now)
    siteLink = models.CharField(max_length=300)

publications/views.py
from django.shortcuts import render


# Create your views here.
def publications_all(request):
    return render(request, 'publications/publications-all.html')

publications/templates/publications/publications-all.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}

    <!-- Blog -->
    <div id="blog" class="section md-padding bg-grey">

        <!-- Container -->
        <div class="container">

            <!-- Row -->
            <div class="row">

                <!-- Section header -->
                <div class="section-header text-center">
                    <h2 class="title">All Research Publications</h2>
                </div>
                <!-- /Section header -->

                <!-- blog -->
                <div class="col-md-4">
                    <div class="blog">
                        <div class="blog-img">
                            <img class="img-responsive" src="{% static 'img/blog1.jpg' %}" alt="">
                        </div>
                        <div class="blog-content">
                            <ul class="blog-meta">
                                <li><i class="fa fa-user"></i>John doe</li>
                                <li><i class="fa fa-clock-o"></i>18 Oct</li>
                                <li><i class="fa fa-comments"></i>57</li>
                            </ul>
                            <h3>Molestie at elementum eu facilisis sed odio</h3>
                            <p>Nec feugiat nisl pretium fusce id velit ut tortor pretium. Nisl purus in mollis nunc sed.
                                Nunc non blandit massa enim nec.</p>
                            <a href="{% url 'blog:blog_single' %}">Read more</a>
                        </div>
                    </div>
                </div>
                <!-- /blog -->

                <!-- blog -->
                <div class="col-md-4">
                    <div class="blog">
                        <div class="blog-img">
                            <img class="img-responsive" src="{% static 'img/blog2.jpg' %}" alt="">
                        </div>
                        <div class="blog-content">
                            <ul class="blog-meta">
                                <li><i class="fa fa-user"></i>John doe</li>
                                <li><i class="fa fa-clock-o"></i>18 Oct</li>
                                <li><i class="fa fa-comments"></i>57</li>
                            </ul>
                            <h3>Molestie at elementum eu facilisis sed odio</h3>
                            <p>Nec feugiat nisl pretium fusce id velit ut tortor pretium. Nisl purus in mollis nunc sed.
                                Nunc non blandit massa enim nec.</p>
                            <a href="blog-single.html">Read more</a>
                        </div>
                    </div>
                </div>
                <!-- /blog -->

                <!-- blog -->
                <div class="col-md-4">
                    <div class="blog">
                        <div class="blog-img">
                            <img class="img-responsive" src="{% static 'img/blog3.jpg' %}" alt="">
                        </div>
                        <div class="blog-content">
                            <ul class="blog-meta">
                                <li><i class="fa fa-user"></i>John doe</li>
                                <li><i class="fa fa-clock-o"></i>18 Oct</li>
                                <li><i class="fa fa-comments"></i>57</li>
                            </ul>
                            <h3>Molestie at elementum eu facilisis sed odio</h3>
                            <p>Nec feugiat nisl pretium fusce id velit ut tortor pretium. Nisl purus in mollis nunc sed.
                                Nunc non blandit massa enim nec.</p>
                            <a href="blog-single.html">Read more</a>
                        </div>
                    </div>
                </div>
                <!-- /blog -->

            </div>
            <!-- /Row -->

        </div>
        <!-- /Container -->

    </div>
    <!-- /Blog -->

{% endblock %}