BRL_Portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('email/', views.email, name='email'),
    path('RD_Project/', include('RD_Projects.urls'), name="RD_Project"),
    path('publications/', include('publications.urls'), name="publications"),
    path('blogs/', include('blogs.urls'), name='blog'),
    path('staff/', include('staff.urls'), name='staff'),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

RD_Projects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

# app_name = "RD_Project"
app_name = 'RD_Project'
urlpatterns = [
    path('Project_Domains/', views.project_domains, name='Project_domains'),
    path('projects_all', views.projects_all, name='projects_all'),
    path('projects_single/<str:id>', views.project_single, name='projects_single'),
    path('services/', views.services, name="services"),
    path('services/<str:id>', views.service_single, name="services_single"),
    path('get_project_detail/', views.get_project_detail, name="get_project_detail"),
    path('get_service_detail/', views.get_service_detail, name="get_service_detail")
]

blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "blog"
urlpatterns = [
    path('blog_all/', views.blog_all, name='blog_all'),
    path('blog_single/<int:id>', views.blog_single, name='blog_single'),
]

publications/urls.py
from django.urls import path, include
from . import views


app_name = "publication"
urlpatterns = [
    path('publications_all/', views.publications_all, name='publications_all'),
]

staff/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# app_name = "RD_Project"
app_name = 'staff'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<int:id>', views.staff_detail, name="staff_detail")
]

templates/Home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


</head>
<body>

<!-- Navbar -->


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">Navbar scroll</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Link 1
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Link 2
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Link 3
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<!-- /Navbar -->



    <!-- Popper JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <!-- bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
</body>
</html>

templates/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Seventh Reality</title>
    <link rel="icon" href="{% static 'img/new bew.png' %}" type="image/icon type">

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CVarela+Round" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Owl Carousel -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/owl.carousel.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/owl.theme.default.css' %}"/>

    <!-- Magnific Popup -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <!-- animate -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" rel="stylesheet">

    <!-- Custom stylesheet -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>




    {% block style %}
    {% endblock %}




    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body>

	<!-- Header -->
	<header>
		<!-- Nav -->
		<nav id="nav" class="navbar navbar-expand-lg navbar-light bg-light navbar-right fixed-top" style="box-shadow: 1px -2px #d2cbcb inset">
			<div class="container">

				<div class="navbar-header">
					<!-- Logo -->
					<div class="navbar-brand">
                        <a href="#carouselExampleControls">
                            <img class="logo" src="{% static 'img/logo 7r.jpg' %}" alt="logo">
                            <img class="logo-alt" src="{% static 'img/new bew.png' %}" alt="logo">
                        </a>
					</div>
					<!-- /Logo -->

					<!-- Collapse nav button -->
					<div class="nav-collapse">
						<span></span>
					</div>
					<!-- /Collapse nav button -->
				</div>

				<!--  Main navigation  -->
				<ul class="main-nav nav navbar-nav navbar-right">
					<li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'RD_Project:projects_all' %}">Products</a></li>
                    <li><a href="{% url 'RD_Project:services' %}">Services</a></li>
{#					<li><a href="{% url 'RD_Project:Project_domains' %}">Portfolio</a></li>#}
{#                    <li><a href="{% url 'publication:publications_all' %}">Publications</a></li>#}
                    <li><a href="{% url 'blog:blog_all' %}">Blogs</a></li>
                    <li><a href="{% url 'staff:index' %}">Team</a></li>
                    <li><a href="#contact">Contact</a></li>
{#                    <li><a href="index.html#service">Services</a></li>#}
{#                    <li><a href="index.html#pricing">Prices</a></li>#}
				</ul>
				<!-- /Main navigation -->

			</div>
		</nav>
		<!-- /Nav -->
	</header>
	<!-- /Header -->

    {% block content %}
    {% endblock %}

    <!-- Contact -->
    <div id="contact" class="section sm-padding" style="background-color: #0f2a5f">
        <!-- Container -->
        <div class="container">
            <!-- Row -->
            <div class="row">


                <div class="col-md-6 row contact-row" style="border-right: 2px solid #0f2a5f; color: #FFFFFF">
                    <!-- contact -->
                    <div class="col-md-12" style="height: 0px; padding-bottom: 50px">
                        <img src="{% static 'img/logo 7R.png' %}" style="max-width: 30% ">
                    </div>
                    <div class="col-md-1">
                        <ul>
                            <li><i class="fa fa-phone"></i></li>
                            <li><i class="fa fa-whatsapp"></i></li>
                            <li><i class="fa fa-envelope"></i></li>
                            <li><i class="fa fa-map-marker"></i></li>
                            <br>
                            <li><i class="fa fa-linkedin"></i></li>
                        </ul>
                    </div>
                    <div class="col-md-2">
                        <ul>
                            <li>Phone</li>
                            <li>WhatsApp</li>
                            <li>Email</li>
                            <li>Address</li>
                            <br>
                            <li>LinkedIn</li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul>
                            <li>+92 300 0041 396</li>
                            <li>+92 300 0041 396</li>
                            <li>XXXXXX@Seventhreality.com</li>
                            <li>14B-Sapphire Block Park View, Multan Road LHR</li>
                            <li><a href="https://www.linkedin.com/company/seventh-reality/" target="_blank">Visit
                                Page</a></li>
                        </ul>
                    </div>
                </div>

                <!-- contact form -->
                <div class="col-md-6">
                    <!-- Section-header -->
                    <div class="section-header text-center" style="margin-bottom: 0px">
                        <h2 class="title" style="color: #FFFFFF;">Get In Touch</h2>
                    </div>
                    <!-- /Section-header -->
                    <form class="contact-form" method="post" action="{% url 'contact' %}">
                        <input type="text" class="input" name="name1" placeholder="Name">
                        <input type="email" class="input" name="email" placeholder="Email">
                        <input type="text" class="input" name="subject" placeholder="Subject">
                        <textarea class="input" name="message" placeholder="Message"></textarea>
                        {% csrf_token %}
                        <button class="main-btn">Send message</button>
                    </form>
                </div>
                <!-- /contact form -->
            </div>
            <!-- /Row -->
        </div>
        <!-- /Container -->
    </div>
    <!-- /Contact -->

    <!-- Footer -->
	<footer id="footer" class="sm-padding bg-dark">

		<!-- Container -->
		<div class="container">

			<!-- Row -->
			<div class="row">

				<div class="col-md-12">

					<!-- footer logo -->
					<div class="footer-logo">
						<a href="index.html"><img src="{% static 'img/logo 7R.png' %}" alt="logo"></a>
					</div>
					<!-- /footer logo -->

					<!-- footer follow -->
					<ul class="footer-follow">
{#						<li><a href="#"><i class="fa fa-facebook"></i></a></li>#}
{#						<li><a href="#"><i class="fa fa-twitter"></i></a></li>#}
{#						<li><a href="#"><i class="fa fa-google-plus"></i></a></li>#}
{#						<li><a href="#"><i class="fa fa-instagram"></i></a></li>#}
						<li><a href="https://www.linkedin.com/company/seventh-reality/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
{#						<li><a href="#"><i class="fa fa-youtube"></i></a></li>#}
					</ul>
					<!-- /footer follow -->

					<!-- footer copyright -->
					<div class="footer-copyright">
						<p>Copyright © 2017. All Rights Reserved. Designed by <a href="{% url 'index' %}">Seventh Reality</a></p>
					</div>
					<!-- /footer copyright -->

				</div>

			</div>
			<!-- /Row -->

		</div>
		<!-- /Container -->

	</footer>
	<!-- /Footer -->

	<!-- Back to top -->
	<div id="back-to-top"></div>
	<!-- /Back to top -->

	<!-- Preloader -->
	<div id="preloader">
		<div class="preloader">
			<span></span>
			<span></span>
			<span></span>
			<span></span>
		</div>
	</div>
	<!-- /Preloader -->

<!-- jQuery Plugins -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.magnific-popup.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.countup.min.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>


    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
     {% block script %}
     {% endblock %}
</body>

</html>

templates/contact.html
{% extends 'basic.html' %}
{% load static %}

{%  block content %}

    <!-- Contact -->
    <div id="contact" class="section md-padding">

        <!-- Container -->
        <div class="container">

            <!-- Row -->
            <div class="row">

                <!-- Section-header -->
                <div class="section-header text-center">
                    <h2 class="title">Get in touch</h2>
                </div>
                <!-- /Section-header -->

                <!-- contact -->
                <div class="col-sm-4">
                    <div class="contact">
                        <i class="fa fa-phone"></i>
                        <h3>Phone</h3>
                        <p>(042) 99029450</p>
                    </div>
                </div>
                <!-- /contact -->

                <!-- contact -->
                <div class="col-sm-4">
                    <div class="contact">
                        <i class="fa fa-envelope"></i>
                        <h3>Email</h3>
                        <p>usman.ghani@uet.edu.pk</p>
                    </div>
                </div>
                <!-- /contact -->

                <!-- contact -->
                <div class="col-sm-4">
                    <div class="contact">
                        <i class="fa fa-map-marker"></i>
                        <h3>Address</h3>
                        <p>Gate-3, KICS UET Lahore</p>
                    </div>
                </div>
                <!-- /contact -->

                <!-- contact form -->
                <div class="col-md-8 col-md-offset-2">
                    <form class="contact-form">
                        <input type="text" class="input" placeholder="Name">
                        <input type="email" class="input" placeholder="Email">
                        <input type="text" class="input" placeholder="Subject">
                        <textarea class="input" placeholder="Message"></textarea>
                        <button class="main-btn">Send message</button>
                    </form>
                </div>
                <!-- /contact form -->

            </div>
            <!-- /Row -->

        </div>
        <!-- /Container -->

    </div>
    <!-- /Contact -->

{% endblock %}

templates/slider.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Homepage Template Bootstrap</title>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" rel="stylesheet">
	<link href="style.css" rel="stylesheet">
    <style>
        .navbar-brand {
	font-family: poppins;
	color: #262626 !important;
	font-size: 25px;
}
.navbar-default .navbar-nav>li>a {
	color: #262626;
	text-transform: uppercase;
	font-weight: bold;
}
a:hover, a:focus {
	color: #fff !important;
}
.banner-area {
	background: #fff;
}
.carousel-inner {
	height: 100vh;
}
.carousel-caption {
	position: static;
}
.carousel-control.left {
	background-image: none;
}
.carousel-control.right {
	background-image: none;
}
.navbar.navbar-default {
	background: transparent;
	border-color: transparent;
}
.carousel-inner {
	background: url(https://images.pexels.com/photos/1731427/pexels-photo-1731427.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);
	-webkit-background-size: cover;
	background-size: cover;
	background-position: center center;
}
.banner-text {
	padding: 20% 0;
}
.banner-text h2 {
	text-transform: uppercase;
	font-size: 47px;
	color: #262626;
	text-shadow: none;
	font-weight: bold;
}
.banner-text p {
	font-size: 18px;
	color: #262626;
	text-shadow: none;
}
.banner-text a {
	background: dodgerblue;
	text-decoration: none;
	color: #fff;
	display: inline-block;
	padding: 15px 30px;
	margin-top: 20px;
	text-transform: uppercase;
	font-weight: bold;
	border-radius: 50px;
}
.carousel-indicators .active {
	background-color: #262626;
}
@media (max-width: 600px) {
	.navbar-brand {
		color: #000;
		padding: 5px;
	}
	.navbar-default .navbar-nav>li>a {
		color: #fff;
	}
	.navbar-default .navbar-nav>li>a:focus, .navbar-default .navbar-nav>li>a:hover {
		color: #333;
		background-color: dodgerblue;
	}
	.navbar-header {
		background: #000;
	}
	.nav.navbar-nav.navbar-right {
		background: #000;
		margin: 0 -15px;
	}
	.banner-text {
		padding: 50% 0;
	}
	.banner-text h2 {
		font-size: 23px;
	}
}

    </style>
</head>
<body>
	<header>
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"><span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button> <a class="navbar-brand" href="#"><img alt="" src="logo.png"></a>
				</div><!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="#">Home</a>
						</li>
						<li>
							<a href="#">About</a>
						</li>
						<li>
							<a href="#">Portfolio</a>
						</li>
						<li>
							<a href="#">Services</a>
						</li>
						<li>
							<a href="#">Contact</a>
						</li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
	</header>
	<div class="banner-area">
		<div class="carousel slide carousel-fade" data-ride="carousel" id="carousel-example-generic">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				<li class="active" data-slide-to="0" data-target="#carousel-example-generic"></li>
				<li data-slide-to="1" data-target="#carousel-example-generic"></li>
				<li data-slide-to="2" data-target="#carousel-example-generic"></li>
			</ol><!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<div class="carousel-caption">
						<div class="container">
							<div class="row">
								<div class="col-md-12 col-sm-12">
									<div class="banner-text">
										<h2 class="animated fadeInUp" style="animation-delay: 2s">Creative Agency</h2>
										<p>Lorem ipsum dolor sit amet.</p><a href="#">Learn More</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="carousel-caption">
						<div class="container">
							<div class="row">
								<div class="col-md-12 col-sm-12">
									<div class="banner-text">
										<h2 class="animated fadeInUp" style="animation-delay: 2s">Graphics design</h2>
										<p>Lorem ipsum dolor sit amet.</p><a href="#">Learn More</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="carousel-caption">
						<div class="container">
							<div class="row">
								<div class="col-md-12 col-sm-12">
									<div class="banner-text">
										<h2 class="animated fadeInUp" style="animation-delay: 2s">Digital Marketing</h2>
										<p>Lorem ipsum dolor sit amet.</p><a href="#">Learn More</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div><!-- Controls -->
			 <a class="left carousel-control" data-slide="prev" href="#carousel-example-generic" role="button"><span aria-hidden="true" class="glyphicon glyphicon-chevron-left"></span> <span class="sr-only">Previous</span></a> <a class="right carousel-control" data-slide="next" href="#carousel-example-generic" role="button"><span aria-hidden="true" class="glyphicon glyphicon-chevron-right"></span> <span class="sr-only">Next</span></a>
		</div>
	</div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js">
	</script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js">
	</script>
</body>
</html>