BRL_Portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('email/', views.email, name='email'),
    path('RD_Project/', include('RD_Projects.urls'), name="RD_Project"),
    path('publications/', include('publications.urls'), name="publications"),
    path('blogs/', include('blogs.urls'), name='blog'),
    path('staff/', include('staff.urls'), name='staff'),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "blog"
urlpatterns = [
    path('blog_all/', views.blog_all, name='blog_all'),
    path('blog_single/<int:id>', views.blog_single, name='blog_single'),
]

staff/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# app_name = "RD_Project"
app_name = 'staff'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<int:id>', views.staff_detail, name="staff_detail")
]

staff/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Employee(models.Model):
    name = models.CharField(max_length=30)
    designation = models.CharField(max_length=80)
    image = models.ImageField(upload_to='images/Staff_Pics')
    profile = RichTextField(default="")

staff/views.py
from django.shortcuts import render
from .models import *
from django.db.models import Q

# Create your views here.
def index(request):
    employees = Employee.objects.all()
    dict_obj = {'employees': employees}
    return render(request, 'staff/index.html', dict_obj)


def staff_detail(requet, id):
    employee = Employee.objects.filter(id=id)
    employees = Employee.objects.filter(~Q(id=id))
    dict_obj = {'employee': employee, 'employees': employees}
    return  render(requet, 'staff/emplyee_profile.html', dict_obj)

staff/templates/staff/emplyee_profile.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}

    {% for e in employee %}
        <div class="container md-padding">
            <div class="container-wrapper">
                <div class="row">
                    <div class="col-md-3">
                        <img src="{{ e.image.url }}" height="200px" width="200px" style="float: left; clear: right; border-radius: 50%">   </div><div class="col-md-7">
                    <h2 style="margin-top: 10px; color: #0f2a5f;">{{ e.name }}</h2>
                    <h4 style="color: #F3581F;">{{ e.designation }}</h4>
                    <p>{{ e.profile|safe }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    <hr>

    {% for employee in employees %}
        <div class="container md-padding">
            <div class="container-wrapper">
                <div class="row">
                    <div class="col-md-3">
                        <img src="{{ employee.image.url }}" height="200px" width="200px"
                             style="float: left; clear: right; border-radius: 50%"></div>
                    <div class="col-md-7">
                        <h2 style="margin-top: 10px; color: #0f2a5f;">{{ employee.name }}</h2>
                        <h4 style="color: #F3581F;">{{ employee.designation }}</h4>
                        <p>{{ employee.profile|safe }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

staff/templates/staff/index.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}

    <!-- Team -->
    <div id="team" class="section md-padding">

        <!-- Container -->
        <div class="container">

            <!-- Row -->
            <div class="row">

                <!-- Section header -->
                <div class="section-header text-center">
                    <h2 class="title">Our Team</h2>
                </div>
                <!-- /Section header -->

                {% for employee in employees %}
                <!-- team -->
                <div class="col-sm-4">

                        <div class="gtco-testimonials">
                            <div class="card text-center"><img class="card-img-top"
                                                               src="{{ employee.image.url }}"
                                                               alt="">
                                <div class="card-body">
                                    <a href="{% url 'staff:staff_detail' employee.id %}"><h5>{{ employee.name }} <br/>
                                        <span> {{ employee.designation }} </span>
                                    </h5></a>
                                    <div class="employee-profile">{{ employee.profile|safe }} </div>
                                    <a href="{% url 'staff:staff_detail' employee.id %}">read more...</a>
                                </div>
                            </div>
                        </div>

                </div>
                <!-- /team -->
                {% endfor %}



            </div>
            <!-- /Row -->

        </div>
        <!-- /Container -->

    </div>
    <!-- /Team -->


{% endblock %}